---
title: "Week 7 - Computational methods for measuring uncertainity - Homework"
author: "Kovács Ádám József, Nguyen Nam Son"
date: "22/10/2020"
output: html_document
---

## Loading the data...

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(out.width = '65%')
knitr::opts_chunk$set(fig.align = 'center')

library(data.table)
library(magrittr)
library(ggplot2)
library(scales)
library(patchwork)

#wd <- file.path("~", "eltecon-datascience")
#setwd(wd)

setwd("C:\\ELTECON\\eltecon-ds")

xp <- fread("week 5-6/experiment_result_HW.csv")

```

## Sampling the KPI of view rate

```{r viewrate, echo = FALSE, eval = FALSE}

###Ádám megoldása

bs_view_rates <-c()

B = 10000
set.seed(1021)
for (i in 1:B) {
  bs_sample = sample(xp[,has_viewed_website], xp[,.N], replace = TRUE)
  bs_view_rates <- c(bs_view_rates, mean(bs_sample))
}

mean(bs_view_rates)

### Szöni megoldása

bootstrapStatistic <- function(x, B = 10000, seed = 1021, fn = mean, ...) {
  if (!is.vector(x)) stop("x needs to be a vector")
  bs_view_rates <- c()
  set.seed(seed)
  
  for (i in 1:B) {
    bs_sample <- sample(x, length(x), replace = TRUE)
    bs_view_rates <- c(bs_view_rates, fn(bs_sample, ...))
  }
  
  return(bs_view_rates)
}

bs_means <- bootstrapStatistic(
  xp[, has_viewed_website], B = 10000, fn = mean
)

paste("The mean of sample means is:", mean(bs_means))

###Ádám

quantile(bs_view_rates, c(0.025,0.975))

###Szöni

quantile(bs_means, c(0.025, 0.975))

bs_medians <- bootstrapStatistic(
  xp[, has_viewed_website], B = 10000, fn = median
)

paste("The median of sample medians is:", median(bs_medians))
quantile(bs_medians, c(0.025, 0.975))

```
**Define test statistic:**

```{r tstat, echo = TRUE}

###Ádám megoldása

sample_mean_control  <- xp[group == "control",  mean(has_viewed_website)]
sample_mean_treatment <- xp[group == "treatment", mean(has_viewed_website)]

sample_diff <- abs(sample_mean_treatment - sample_mean_control)
sample_diff

###Szöni megoldása

sample_view_diff <- abs(xp[group == "treatment", mean(has_viewed_website)] - xp[group == "control", mean(has_viewed_website)])

paste("The t-stat of the difference between groups is:", sample_view_diff)

```

## Permutation hypothesis testing

**Calculate distribution of test statistic under H0**

```{r distribution, echo = TRUE}

###Ádám megoldása

B = 10000
  perm_sample_diffs <- data.table(perm_id = integer(), perm_diff = numeric())

  set.seed(1021)
  for (i in 1:B) {
    perm_sample <- data.table(
      group = xp[, group],
      has_viewed = sample(xp[, has_viewed_website], xp[,.N], replace = FALSE)
    )

    perm_sample_diffs <- rbind(
      perm_sample_diffs,
      data.table(
        perm_id = i,
        perm_diff = perm_sample[group == "treatment", mean(has_viewed)] - perm_sample[group == "control", mean(has_viewed)]
      )
    )
  }

###Szöni megoldása

  B = 10000
  perm_sample_diffs <- data.table(perm_id = integer(), perm_diff = numeric())
  set.seed(1021)
  for (i in 1:B) {
    perm_sample <- data.table(
      group = xp[, group],
      view_rate = sample(xp[, has_viewed_website], xp[, .N], replace = FALSE)
    )
    perm_sample_diffs <- rbind(
      perm_sample_diffs,
      data.table(
        perm_id = i,
        perm_diff = perm_sample[group == "treatment", mean(view_rate)] - perm_sample[group == "control", mean(view_rate)]
      )
    )
  }
  
  ###Ezek nekem vmiért nem futnak le.... lehet csak türelmetlen vagyok / szar a gépem
  
```

## Permutation hypothesis testing

```{r plot}
###Ádám megoldása
ggplot(perm_sample_diffs, aes(x = perm_diff)) +
    geom_density() +
    geom_vline(aes(xintercept = sample_view_diff), color = "blue") +
    geom_vline(aes(xintercept = -1 * sample_viewt_diff), color = "blue") +
    geom_vline(aes(xintercept = perm_sample_diffs[, quantile(perm_diff, 0.025)]), color = "red") +
    geom_vline(aes(xintercept = perm_sample_diffs[, quantile(perm_diff, 0.975)]), color = "red") +
    labs(
      x = "View rate Diff.", y = NULL,
      title = "Diff. in View rate under H0",
      subtitle = "<span style = 'color: blue;'>View rate diff. in sample</span> vs <span style = 'color: red;'>95% CI</span>"
    ) +
    theme_classic() +
    theme(text = element_text(size = 20)) +
    theme(plot.subtitle = ggtext::element_markdown())

###Szöni megoldása

ggplot(perm_sample_diffs, aes(x = perm_diff)) +
    geom_density() +
    geom_vline(aes(xintercept = sample_view_diff), color = "blue") +
    geom_vline(aes(xintercept = -1 * sample_view_diff), color = "blue") +
    geom_vline(aes(xintercept = perm_sample_diffs[, quantile(perm_diff, 0.025)]), color = "red") +
    geom_vline(aes(xintercept = perm_sample_diffs[, quantile(perm_diff, 0.975)]), color = "red") +
    labs(
      x = "View rate differences", y = NULL,
      title = "Diff. in view rates across groups under H0",
      subtitle = "<span style = 'color: blue;'>View diff. in sample</span> vs <span style = 'color: red;'>95% CI</span>"
    ) +
    theme_classic() +
    theme(text = element_text(size = 10)) +
    theme(plot.subtitle = ggtext::element_markdown())

```

## Permutation hypothesis testing

**Calculate p-value**
```{r pvalue, echo = TRUE}
###Ádám megoldása

p_value <- perm_sample_diffs[,
  sum(sample_view_diff < abs(perm_diff)) / .N
]

print(p_value)


### SZöni megoldása
p_value <- perm_sample_diffs[,
  sum(sample_view_diff < abs(perm_diff)) / .N
]
paste("The pvalue of the test is:", p_value)

```
**Since the p-value is zero, we can reject the null-hypothesis that the view rate of the groups are the same**

***
